### ISSUE TITLE
NoSuchFieldError when passing version string to ScallopConf subclass

### ISSUE THREAD

**Issue by clark-archer** [scallop/scallop#100]
I've run into an issue when I try to parameterize my ScallopConf subclass (to be reused by a few applications with identical config other than version strings and banner messages).

```
import org.rogach.scallop.ScallopConf
class MyConfig(versionString: String, args: Seq[String]) extends ScallopConf(args) {
  version(versionString)
  ...
}

object MyApp {
  val Version = "0.0.1"
  val VersionString = s"MyApp $Version"
  def main(args: Array[String]): Unit = {
    val config = new Config(VersionString, args)
  }
}
```

```
Exception in thread "main" java.lang.NoSuchFieldError: versionString
    at Config.versionString(Config.scala:2)
    at Config$delayedInit$body.apply(Config.scala:3)
    at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
    at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
    at org.rogach.scallop.AfterInit$class.delayedInit(AfterInit.scala:12)
    at org.rogach.scallop.ScallopConf.delayedInit(ScallopConf.scala:26)
    at Config.<init>(Config.scala:2)
    at MyApp$.main(MyApp.scala:5)
```

Not sure what I'm doing wrong exactly or if this is a bug?

**Comment by clark-archer** [comment]
Actually I think I just showed some Scala-related ignorance.  Apparently I must declare my subclass like so:

`class MyConfig(val versionString: String, args: Seq[String]) extends ScallopConf(args) {
`

With this class declaration I get the expected results.
