### ISSUE TITLE
NoSuchMethod error with singleArgConverter

### ISSUE THREAD

**Issue by chipsenkbeil** [scallop/scallop#146]
I recently upgraded from version `2.0.5` to `3.0.3` of _scallop_. It all checks out and compiles, but I'm getting a `NoSuchMethod` exception when attempting to run my application.

```sbt
> compile
[info] Compiling 1 Scala source to /Users/senk/projects/scala-site-generator/site-generator/target/scala-2.10/classes...
[info] Compiling 7 Scala sources to /Users/senk/projects/scala-site-generator/site-generator/target/scala-2.10/classes...
[success] Total time: 7 s, completed 05-Jul-2017 14:26:00
> sitegen:run --help
[warn] sitegen:run::javaOptions will be ignored, sitegen:run::fork is set to false
[info] Running org.senkbeil.sitegen.Main --help
[error] (run-main-2) java.lang.NoSuchMethodError: org.rogach.scallop.package$.singleArgConverter(Lscala/Function1;Lscala/PartialFunction;)Lorg/rogach/scallop/ValueConverter;
java.lang.NoSuchMethodError: org.rogach.scallop.package$.singleArgConverter(Lscala/Function1;Lscala/PartialFunction;)Lorg/rogach/scallop/ValueConverter;
	at org.senkbeil.sitegen.Config.<init>(Config.scala:43)
	at org.senkbeil.sitegen.Main$.main(Main.scala:14)
	at org.senkbeil.sitegen.Main.main(Main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```

The code in question is the following:
```scala
package org.senkbeil.sitegen

import java.net.URL
import java.nio.file.Paths

import org.rogach.scallop._

/**
 * Represents the CLI configuration for the site generator tool.
 *
 * @param arguments The list of arguments fed into the CLI (same
 *                  arguments that are fed into the main method)
 */
class Config(arguments: Seq[String]) extends ScallopConf(arguments) {

  // SUBCOMMANDS AND WHATNOT ...
 
  /** Aids in converting to a low level value. */
  private implicit val logLevelConverter =
    singleArgConverter[Logger.Level.Level](n =>
      Logger.Level.withName(n.trim.toLowerCase.capitalize), {
      case _: Throwable => Left(
        "Choices are " +
        Logger.Level.values.mkString(", ")
      )
    })

  // LOTS OF OPTIONS AND WHATNOT ...

  // Display our default values in our help menu
  appendDefaultToDescription = true

  // Enable displaying subcommands in help
  shortSubcommandsHelp(true)

  // Process arguments
  verify()
}
```

**Comment by chipsenkbeil** [comment]
Nevermind. Was an issue with me using an outdated version of the plugin from a `publishLocal`.
