### ISSUE TITLE
Verify() method with scala version `2.10.5` not working.

### ISSUE THREAD

**Issue by rajeshsindhu21** [scallop/scallop#161]
Hi, 

I am using scalaVersion := "**2.10.5**" and libraryDependencies += "org.rogach" %% "scallop" % "**3.1.2**".

Getting following error:
`Exception in thread "main" java.lang.NoSuchMethodError: scala.collection.immutable.$colon$colon.hd$1()Ljava/lang/Object;
	at org.rogach.scallop.DefaultConverters$$anon$2.parse(DefaultConverters.scala:27)
	at org.rogach.scallop.ValueConverter$class.parseCached(ValueConverter.scala:21)
	at org.rogach.scallop.DefaultConverters$$anon$2.parseCached(DefaultConverters.scala:24)
	at org.rogach.scallop.Scallop$$anonfun$verify$17.apply(Scallop.scala:632)
	at org.rogach.scallop.Scallop$$anonfun$verify$17.apply(Scallop.scala:630)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.rogach.scallop.Scallop.verify(Scallop.scala:630)
	at org.rogach.scallop.ScallopConfBase.verifyBuilder(ScallopConfBase.scala:405)
	at org.rogach.scallop.ScallopConfBase.verify(ScallopConfBase.scala:744)
	at com.unity3d.ads.conf.OperativeEventConverterConf.<init>(OperativeEventConverterConf.scala:50)
	at com.unity3d.ads.analytics.TestClass$.main(TestClass.scala:51)
	at com.unity3d.ads.analytics.TestClass.main(TestClass.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:738)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:187)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:212)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:126)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
` 

The exact same code is working fine with scalaVersion := "**2.11.8**"

Unfortunately, I have to use `2.10.5`  because I am using spark version `1.6`.

sample code:

`import org.rogach.scallop.{ScallopConf, ScallopOption, Serialization, ValueConverter, singleArgConverter}

class TestClass(args: Seq[String]) extends ScallopConf(args) with Serialization {

  val testInput: ScallopOption[String] =
    opt[String](
      name = "test.input",
      descr = "test",
      required = false,
      default = Option("testPath"))
    verify()
}
` 

Is there any workaround I can use here to make it work with scala **2.10.5**?

**Comment by Rogach** [comment]
Hi!

I attempted to compile your example, and it runs fine ([test project](https://gist.github.com/Rogach/6e41d137c0a5ecbb29a1363c5760ce66)).

I believe that the problem is located in your compiler/library/dependencies configuration, not in Scallop.

The error points to [this line](https://github.com/scallop/scallop/blob/develop/src/main/scala/org.rogach.scallop/DefaultConverters.scala#L27):

```scala
case (_, i :: Nil) :: Nil =>
```

And complains that `::.hd` is absent. If we look at Scala source, that field is present in Scala 2.10 ([link to source code](https://github.com/scala/scala/blob/v2.10.5/src/library/scala/collection/immutable/List.scala#L356)), but absent from 2.11.8 ([link to source code](https://github.com/scala/scala/blob/v2.11.8/src/library/scala/collection/immutable/List.scala#L439)). Between those two releases internal field `::.hd` was renamed to `::.head`.

So my guess will be that your classpath contains `scallop_2.10.5` jar with scala library at some newer version. Can you look at the exact classpath used to start the failing `java` process?

**Comment by rajeshsindhu21** [comment]
Thank you @Rogach, this is why my spark submit were failing.

> I was using spark 2.1 to run code compiled with spark 1.6 version. apparently, 1.6 uses scala 2.10.. while spark 2.1 uses scala 2.11...
