### ISSUE TITLE
type annotation will cause OptionNameGuessingFailure exception

### ISSUE THREAD

**Issue by can-007** [scallop/scallop#202]
I have code snippet as the following:
```
import org.rogach.scallop.{ScallopConf, Subcommand}

class ValidationConf(arguments: Seq[String]) extends ScallopConf (arguments){
  val any: Subcommand = new Subcommand("any") {
    val apples = opt[Int]()
    val bananas = opt[Int]()
    val coconuts = opt[Int]()
    dependsOnAny(apples, List(bananas, coconuts))
  }
  addSubcommand(any)
  verify()
}

object TempMain extends App {
  var validationConf = new ValidationConf(List("any", "-a", "1", "-b", "2"))
}
```

Then I get the errors as the following:
```
"C:\Program Files\Java\jdk-11.0.1\bin\java.exe" "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3.3\lib\idea_rt.jar=54844:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3.3\bin" -Dfile.encoding=UTF-8 -classpath C:\work\scala\Examples\target\scala-2.13\classes;C:\Users\liuca\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\rogach\scallop_2.13\3.4.0\scallop_2.13-3.4.0.jar;C:\Users\liuca\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scala-lang\scala-library\2.13.1\scala-library-2.13.1.jar TempMain

Exception in thread "main" org.rogach.scallop.exceptions.OptionNameGuessingFailure: Failed to guess option name for one of the options
	at org.rogach.scallop.ScallopConfBase.verifyConf(ScallopConfBase.scala:819)
	at org.rogach.scallop.ScallopConfBase.addSubcommand(ScallopConfBase.scala:46)
	at ValidationConf.<init>(ScallopMain.scala:54)
	at TempMain$.delayedEndpoint$TempMain$1(TempMain.scala:15)
	at TempMain$delayedInit$body.apply(TempMain.scala:14)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1(App.scala:73)
	at scala.App.$anonfun$main$1$adapted(App.scala:73)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:553)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:551)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:921)
	at scala.App.main(App.scala:73)
	at scala.App.main$(App.scala:71)
	at TempMain$.main(TempMain.scala:14)
	at TempMain.main(TempMain.scala)

Process finished with exit code 1

```

If I change the following line:
` val any: Subcommand = new Subcommand("any") {`
into the following line:
` val any = new Subcommand("any") {`
Then everything works fine.

Anybody knows why?

I use Intellij IDEA 2019.3.3 Community Edition, Build # IC193.6494.35 Built on 2020.2.11.
I use JDK 11.0.1

**Comment by Rogach** [comment]
When you do

```scala
val any = new Subcommand("any") {
  val apples = opt[Int]()
  val bananas = opt[Int]()
  val coconuts = opt[Int]()
}
```
then `any` is not actually `Subcommand`, it's anonymous class that extends `Subcommand` and defines additional accessor methods `apples`, `bananas` and `coconuts`.

When you explicitly narrow down the definition to `Subcommand` only, the compiler decides to mark these methods private, as it assumes that you explicitly stated that you do not need them outside. Indeed, it will even throw a compilation error if you try to access them. For example, if you do the following:

```scala
val any: Subcommand = new Subcommand("any") {
  val apples = opt[Int]()
  val bananas = opt[Int]()
  val coconuts = opt[Int]()
}
println(any.apples)
```
You will get an error: `value apples is not a member of org.rogach.scallop.Subcommand`

And since they are private, Scallop is unable to find these methods when trying to guess option names, and you get this error.

Solution: do not mark the value with explicit type annotation. If you absolutely need the type annotations on all values for some reason, then you can transform anonymous class into explicitly named one:

```scala
    class ValidationConf(arguments: Seq[String]) extends ScallopConf (arguments){
      class SubcommandAny extends Subcommand("any") {
        val apples = opt[Int]()
        val bananas = opt[Int]()
        val coconuts = opt[Int]()
        dependsOnAny(apples, List(bananas, coconuts))
      }
      val any: SubcommandAny = new SubcommandAny
      addSubcommand(any)
      verify()
    }

```
