### ISSUE TITLE
Reflective performOptionNameGuessing (verify) fails with IllegalAccessException on Scala 3.0.0-M3

### ISSUE THREAD

**Issue by Sciss** [scallop/scallop#226]
Example:
```scala
import org.rogach.scallop._

import java.io.File
import java.nio.charset.StandardCharsets
import scala.io.Source

object Translate {
  case class Config(input: File, output: Option[File], srt: Boolean, charset: String)

  def main(args: Array[String]): Unit = {
    object parse extends ScallopConf(args.toSeq) {
      val srt     = toggle()
      val output  = opt[File]()
      val charset = opt[String](default = Some(StandardCharsets.UTF_8.name()))
      val input   = trailArg[File]()
      verify()   // line 16
      val conf = Config(input = input(), output = output.toOption, srt = srt(), charset = charset())
    }
    parse.conf
  }
}
```
Running this:
```
[info] running Translate 
[error] (run-main-0) java.lang.IllegalAccessException: class org.rogach.scallop.ScallopConf cannot access a member of class Translate$parse$1$ with modifiers "public"
[error] java.lang.IllegalAccessException: class org.rogach.scallop.ScallopConf cannot access a member of class Translate$parse$1$ with modifiers "public"
[error]     at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:361)
[error]     at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:591)
[error]     at java.base/java.lang.reflect.Method.invoke(Method.java:558)
[error]     at org.rogach.scallop.ScallopConf.$anonfun$5(ScallopConf.scala:27)
[error]     at scala.collection.ArrayOps$.map$extension(ArrayOps.scala:924)
[error]     at org.rogach.scallop.ScallopConf.performOptionNameGuessing(ScallopConf.scala:29)
[error]     at org.rogach.scallop.ScallopConfBase.verifyConf(ScallopConfBase.scala:1069)
[error]     at org.rogach.scallop.ScallopConfBase.verify(ScallopConfBase.scala:1086)
[error]     at Translate$parse$1$.<init>(Translate.scala:16)
```
(sbt 1.4.7, OpenJDK 11 Linux)

**Comment by Rogach** [comment]
I can verify this on Java 8, but not on Scala 2, so something is probably a little different in Scala 3.

I added `.setAccessible(true)` call before we invoke the methods reflectively, this seems to make the error go away (I feel that is a bit dirty, but see no other alternative). Please test this snapshot, will it make the problem go away on your end?

```scala
resolvers += "Sonatype OSS Snapshots" at "https://oss.sonatype.org/content/repositories/snapshots"
libraryDependencies += "org.rogach" %% "scallop" % "4.0.3-SNAPSHOT"
```

**Comment by Rogach** [comment]
I hope the issue is solved on your end. I'll release the change in the next version, to safeguard against similar errors in the future.
