### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: org/rogach/scallop/ScallopConf

### ISSUE THREAD

**Issue by TomaszCPL** [scallop/scallop#229]
Hi,

I am struggling to resolve the following error message:
```
Warning: Ignoring non-Spark config property: eventLog.rolloverIntervalSeconds
Exception in thread "main" java.lang.NoClassDefFoundError: org/rogach/scallop/ScallopConf
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:757)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at io.delta.connectors.spark.jdbc.ImportRunner$.main(ImportRunner.scala:28)
	at io.delta.connectors.spark.jdbc.ImportRunner.main(ImportRunner.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:928)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1007)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1016)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: org.rogach.scallop.ScallopConf
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 25 more
```

I have tried to apply the solution suggested here https://github.com/scallop/scallop/issues/195. However, the build file I use seems to be fine from this perspective. Here are the relevant extracts:
```
lazy val commonSettings = Seq(
  organization := "io.delta",
  scalaVersion := "2.12.8",
  fork := true,
  javacOptions ++= Seq("-source", "1.8", "-target", "1.8"),
  scalacOptions += "-target:jvm-1.8",
  // Configurations to speed up tests and reduce memory footprint
  javaOptions in Test ++= Seq(
    "-Dspark.ui.enabled=false",
    "-Dspark.ui.showConsoleProgress=false",
    "-Dspark.databricks.delta.snapshotPartitions=2",
    "-Dspark.sql.shuffle.partitions=5",
    "-Ddelta.log.cacheSize=3",
    "-Dspark.sql.sources.parallelPartitionDiscovery.parallelism=5",
    "-Xmx1024m"
  ),
  compileScalastyle := scalastyle.in(Compile).toTask("").value,
  (compile in Compile) := ((compile in Compile) dependsOn compileScalastyle).value,
  testScalastyle := scalastyle.in(Test).toTask("").value,
  (test in Test) := ((test in Test) dependsOn testScalastyle).value
)

lazy val sqlDeltaImport = (project in file("sql-delta-import"))
  .settings (
    name := "sql-delta-import",
    commonSettings,
    publishArtifact := scalaBinaryVersion.value == "2.12",
    publishArtifact in Test := false,
    libraryDependencies ++= Seq(
      "org.apache.spark" %% "spark-sql" % sparkVersion % "provided",
      "io.delta" % "delta-core_2.12" % "0.7.0" % "provided",
      "org.rogach" %% "scallop" % "3.5.0",
      "org.scalatest" %% "scalatest" % "3.1.1" % "test",
      "com.h2database" % "h2" % "1.4.200" % "test",
      "org.apache.spark" % "spark-catalyst_2.12" % "3.0.0" % "test",
      "org.apache.spark" % "spark-core_2.12" % "3.0.0" % "test",
      "org.apache.spark" % "spark-sql_2.12" % "3.0.0" % "test"
    )
  )
  .settings(releaseSettings)

```

I can hardly find any further info on this, so I would appreciate any hints!

**Comment by Rogach** [comment]
Can you create a reproducer project? You build file looks okay to my eyes, no obvious issues.

**Comment by Rogach** [comment]
I'm not very familiar with Spark deployment process. Could it be that you use the jar generated by `sqlDeltaImport/publishArtifact` directly?

**Comment by TomaszCPL** [comment]
@Rogach Thank you for your answer! It happens when I am trying to use this repo https://github.com/shtusha/connectors . Precisely the https://tech.scribd.com/blog/2021/introducing-sql-delta-import.html functionality. I am running the spark-submit command and get this message. I know it's more related to the /shtusha/connectors repo, so feel free to close this issue at any point. I am just looking for any hints on how to solve it. Does the scallop require a fat jar? I've been using package/publish local, since assembly kept failing for me and I wonder if this could be an issue.

**Comment by Rogach** [comment]
I think that fat jar is needed, otherwise Scallop classes are not included in the artifact and thus you get NoClassDefFoundError exceptions.

What assembly errors are you getting? If merge conflicts, then that's pretty standard, you can fix them as described in https://github.com/sbt/sbt-assembly#merge-strategy

**Comment by TomaszCPL** [comment]
I have managed to solve the issue by creating a fat jar. Closing.
