### ISSUE TITLE
Cannot use single hypen as argument

### ISSUE THREAD

**Issue by stevedlawrence** [scallop/scallop#31]
It would be nice to be able to use a single hyphen (-) as the value of an argument, for both trailing arguments and optional arguments. This is often used to imply stdin or stdout, for example:

```
$ foo --output - 
```

displays the data to stdout. Below, the hyphen tells bar to read data from stdin rather than a file.

```
$ echo test | bar -
```

Right now (on 0.6.4), this

```
object Conf extends ScallopConf(args) {
  val output = opt[String]("output")
  val input = trailArg[String]("input")
}
```

with this

```
$ foo --output - -
```

 causes the following exception

```
    Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 1
      at java.lang.String.charAt(String.java:658)
      at scala.collection.immutable.StringOps.apply(StringOps.scala:39)
      at org.rogach.scallop.Scallop.parse(Scallop.scala:114)
      at org.rogach.scallop.Scallop.parse(Scallop.scala:51)
      at org.rogach.scallop.Scallop.org$rogach$scallop$Scallop$$parsed(Scallop.scala:154)
```

**Comment by Rogach** [comment]
Sorry for taking so long - was away from computer.

Thanks a lot for this pull request! I merged it, and will cut a release right now.
