### ISSUE TITLE
Any way to match nested subcommands?

### ISSUE THREAD

**Issue by geekonek** [scallop/scallop#97]
Is there any way to match nested subcommand? Trying to do something like this 

``` scala
 Conf.subcommand match {
    case Some(Conf.sub1) => {
      Conf.sub1.subcommand match {
        case Some(Conf.sub1.sub1a) => something1();
        case Some(Conf.sub1.sub1b) => something2();
      }
    };
  }
```

but whatever I try i end up with

```
Exception in thread "main" java.lang.AssertionError: assertion failed: You shouldn't call 'subcommand' on subcommand object
        at scala.Predef$.assert(Predef.scala:179)
        at org.rogach.scallop.ScallopConf.subcommand(ScallopConf.scala:64)
```

**Comment by Rogach** [comment]
You can try matching on full subcommand list:

``` scala
Conf.subcommands match {
  case List(Conf.sub1, Conf.sub1.sub1a) => something1()
  case List(Conf.sub1, Conf.sub1.sub1b) => something2()
}
```

**Comment by Rogach** [comment]
Or even shorter, since nested subcommand implies that all its parents are present:

```scala
Conf.subcommand match {
  case Conf.sub1.sub1a => something1()
  case Conf.sub1.sub1b => something2()
}
```

**Comment by geekonek** [comment]
That works, thanks. 
But kind of long if you have few levels of nested subcommands.
